# pubspec.yaml
name: company_hub
description: Company Hub Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.2
  intl: ^0.20.2
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  pull_to_refresh: ^2.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/images/dark.png
    - assets/images/logo3.png
    - assets/images/logow.png
    - assets/images/logo2.png
    - assets/images/micro.png
    - assets/icons/Chatbot_Red.png